/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
  public static void main(String[] args) {
    CarDirector director = new CarDirector();

    CarObjectBuilder racingObjectBuilder = new CarObjectBuilder();
    director.makeRacingCar(racingObjectBuilder);
    Car racingCar = racingObjectBuilder.getResult();
    System.out.println(racingCar);

    CarListingBuilder racingListingBuilder = new CarListingBuilder();
    director.makeRacingCar(racingListingBuilder);
    String racingListing = racingListingBuilder.getResult();
    System.out.println(racingListing);

    CarObjectBuilder regularObjectBuilder = new CarObjectBuilder();
    director.makeRegularCar(regularObjectBuilder);
    Car regularCar = regularObjectBuilder.getResult();
    System.out.println(regularCar);

    CarListingBuilder regularListingBuilder = new CarListingBuilder();
    director.makeRegularCar(regularListingBuilder);
    String regularListing = regularListingBuilder.getResult();
    System.out.println(regularListing);

    try {
      new CarObjectBuilder().setBrand("Toyota").getResult();
    } catch (IllegalStateException e) {
      System.out.println("validation error: " + e.getMessage());
    }
  }
}
